apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: rag3-aug9-1-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  rag3-aug9-1-database
    app.kubernetes.io/part-of: rag3-aug9-1  
  name: rag3-aug9-1-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  rag3-aug9-1-database
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  rag3-aug9-1-database
    spec:
      containers:
      - image: quay.io/redhat-ai-dev/chroma:latest
        name: database
        ports:
        - containerPort: 8000
        securityContext:
          runAsNonRoot: true
