apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag3-aug9-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag3-aug9-1:a9198cc7036f3bfccb018c62ac5a7bc5791bfd73@sha256:36812759e97c048073a3c486a99e9be7af7474173e5a36a4eb6953fbb3b4f83f # use pre-built to bootstrap 
          name: app-inference
